### ISSUE TITLE
.desktop file

### ISSUE THREAD

**Issue by orschiro** [mildmojo/caffeine-plus#3]
Dear @mildmojo,

Many thanks for providing caffeine-plus. I am also one of the persons who prefers to have an indicator icon. 

One small question:

I noticed that caffeine-plus (in comparison to caffeine) does not provide a `.desktop` file. This means I can only launch it from the command line but not from the start menu. Do you plan to integrate a desktop file in the future?

Thankfully,

Robert

**Comment by mildmojo** [comment]
The `caffeine-plus.desktop` file is installed to `/usr/local/share/applications/` in both caffeine and caffeine-plus by default. Copying it to `/usr/share/applications/` or `~/.local/share/applications` should add it to your launcher menu.

You could've also installed the script with `sudo python setup.py install --prefix /usr` to have it install its files under `/usr` instead of the default `/usr/local`. That would likely place the .desktop file where your launcher could find it.

**Comment by mildmojo** [comment]
It looks like the installed .desktop file expects to find the script at `/usr/bin/caffeine-plus`, so you'll need to edit it to point to `/usr/local/bin/caffeine-plus`, copy `/usr/local/bin/caffeine-plus` to `/usr/bin`, or install caffeine-plus with `--prefix /usr` like I noted in the previous comment.

**Comment by mildmojo** [comment]
I've updated the installation command in the README to use `--prefix /usr` to help other people out.

**Comment by orschiro** [comment]
> It looks like the installed .desktop file expects to find the script at /usr/bin/caffeine-plus, so you'll need to edit it to point to /usr/local/bin/caffeine-plus, copy /usr/local/bin/caffeine-plus to /usr/bin, or install caffeine-plus with --prefix /usr like I noted in the previous comment.

Thank you! Can this fix be directly implemented in the package provided at `ppa:nilarimogard/webupd8`?

**Comment by mildmojo** [comment]
I'm not affiliated with packaging folks, and I don't see a way to contact that PPA's maintainer. Would you be willing to look into it? I'm sure their package could be updated to install to `/usr`.

**Comment by orschiro** [comment]
Yes, I contacted him.

Looking forward to an update soon. 

Thank you for your help!

Robert
