### ISSUE TITLE
empty and full icons don't get found

### ISSUE THREAD

**Issue by timrae** [mildmojo/caffeine-plus#5]
Hi I just installed this on Ubunutu 14.04LTS and I found that the icon was always like this regardless of toggling state:

![caffeine](https://cloud.githubusercontent.com/assets/2818274/11083055/2724a126-886e-11e5-9766-a26c14b1d8f8.png)

It seems that `AppIndicator` will choose `caffeine.png` if `caffeine-some-other-text.png` isn't found. The icons were copied over as specified in the install script, but it seems that's not what Ubuntu expects (maybe it doesn't like having them in the "status" folder?), because if I go and manually copy the empty and full icons up a few levels to `/usr/share/icons` then it starts behaving correctly.

I'm new to linux so I'm not too sure where the icons are supposed to go

**Comment by mildmojo** [comment]
Hi. Sorry about that. There should be no harm in putting them in `/usr/share/icons`, it's just a little less convenient.

This fork was created because the [upstream Caffeine project](https://launchpad.net/caffeine) had dropped the ability to manually toggle "stay awake" through the status bar, but as of 2.8 I think he's included a separate `caffeine-indicator` program that adds the status bar indicator back. You might try that version.

I haven't had a chance to give it a try myself. If it works for toggling through the status bar, I'll deprecate and this project.

**Comment by timrae** [comment]
Thanks for the reply, I just tried it out and it works! So I think you can safely deprecate this project

``` bash
sudo add-apt-repository ppa:caffeine-developers/ppa
sudo apt-get update
sudo apt-get install caffeine
caffeine
caffeine-indicator
```

If you get an error like `Xlib.error.DisplayConnectionError: Can't connect to display ":0"` then install the .deb patch in [bug 1460226](https://bugs.launchpad.net/caffeine/+bug/1460226) (comment 17)
